### ISSUE TITLE
Course/ABOUT : subscribe button : hide the reference

### ISSUE THREAD

**Issue by fabienstreit** [rue89-tech/edx-theme#7]
only keep "s'inscrire"

http://www.awesomescreenshot.com/image/603478/1987a8e61051028303274f7a91380ef7
http://rue89-theme2.sandbox.opencraft.com/courses/course-v1:edX+DemoX+Demo_Course/about

**Comment by antoviaque** [comment]
@fabienstreit @mperrien To avoid a change in the template, since the text you want to use is static ("s'inscrire"), an option would be to use pseudo-elements to do this. It's a hack, but it might be tricky to get the template change to be accepted upstream, so it might still be better than code drift:

```
.content-wrapper section.course-info header.course-profile .intro-inner-wrapper .table .intro .main-cta a.register {
    text-indent: -9999px;
    line-height: 0;
}
.content-wrapper section.course-info header.course-profile .intro-inner-wrapper .table .intro .main-cta a.register::after {
    content: "S'inscrire";
    text-indent: 0;
    display: block;
    line-height: initial;
}
```

**Comment by mperrien** [comment]
Fixed

**Comment by mperrien** [comment]
@antoviaque It's the kind of hack I've been using throughout the theme...

**Comment by antoviaque** [comment]
@mperrien Ok : ) I wouldn't know because I let Sven review your PR, but that makes sense yes.
